// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNoytosVF1qDar90RLfEbAsUNwI0zCAk',
    appId: '1:644712028793:web:570989500495e3349752a8',
    messagingSenderId: '644712028793',
    projectId: 'maxliss-71841',
    authDomain: 'maxliss-71841.firebaseapp.com',
    databaseURL: 'https://maxliss-71841-default-rtdb.firebaseio.com',
    storageBucket: 'maxliss-71841.firebasestorage.app',
    measurementId: 'G-841ZG97VX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnOS6TBeiaRZVPVoapi1WfX42Pa29yj3o',
    appId: '1:644712028793:android:3f7c88e6fb1aaf8e9752a8',
    messagingSenderId: '644712028793',
    projectId: 'maxliss-71841',
    databaseURL: 'https://maxliss-71841-default-rtdb.firebaseio.com',
    storageBucket: 'maxliss-71841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJW0DlfLrcCj8tpbhSyUy6gI0XS8Jj-Q',
    appId: '1:644712028793:ios:2f5bbdaee48e28759752a8',
    messagingSenderId: '644712028793',
    projectId: 'maxliss-71841',
    databaseURL: 'https://maxliss-71841-default-rtdb.firebaseio.com',
    storageBucket: 'maxliss-71841.firebasestorage.app',
    iosBundleId: 'com.evyx.expert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJW0DlfLrcCj8tpbhSyUy6gI0XS8Jj-Q',
    appId: '1:644712028793:ios:0022bddfc0892b069752a8',
    messagingSenderId: '644712028793',
    projectId: 'maxliss-71841',
    databaseURL: 'https://maxliss-71841-default-rtdb.firebaseio.com',
    storageBucket: 'maxliss-71841.firebasestorage.app',
    iosBundleId: 'com.example.expert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNoytosVF1qDar90RLfEbAsUNwI0zCAk',
    appId: '1:644712028793:web:82d46a3c92cb128b9752a8',
    messagingSenderId: '644712028793',
    projectId: 'maxliss-71841',
    authDomain: 'maxliss-71841.firebaseapp.com',
    databaseURL: 'https://maxliss-71841-default-rtdb.firebaseio.com',
    storageBucket: 'maxliss-71841.firebasestorage.app',
    measurementId: 'G-LKLGQ4ZMTN',
  );

}