// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCphV3SeCpIXsr9aPPdcKHgUI9IH16rsBE',
    appId: '1:629503468316:web:e4811e684516642707d0d9',
    messagingSenderId: '629503468316',
    projectId: 'maxliss',
    authDomain: 'maxliss.firebaseapp.com',
    storageBucket: 'maxliss.firebasestorage.app',
    measurementId: 'G-BTECR98WZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjYMTpO19Mjaiwbem__ki5HyTv97ukVcE',
    appId: '1:629503468316:android:0635da892753706307d0d9',
    messagingSenderId: '629503468316',
    projectId: 'maxliss',
    storageBucket: 'maxliss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrzkBRbR0m_aQ-QFkv0ETI7yNbmb9s7SU',
    appId: '1:629503468316:ios:cb7a491cc526688a07d0d9',
    messagingSenderId: '629503468316',
    projectId: 'maxliss',
    storageBucket: 'maxliss.firebasestorage.app',
    iosBundleId: 'com.example.expert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrzkBRbR0m_aQ-QFkv0ETI7yNbmb9s7SU',
    appId: '1:629503468316:ios:cb7a491cc526688a07d0d9',
    messagingSenderId: '629503468316',
    projectId: 'maxliss',
    storageBucket: 'maxliss.firebasestorage.app',
    iosBundleId: 'com.example.expert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCphV3SeCpIXsr9aPPdcKHgUI9IH16rsBE',
    appId: '1:629503468316:web:7f7a6adb1845cbc707d0d9',
    messagingSenderId: '629503468316',
    projectId: 'maxliss',
    authDomain: 'maxliss.firebaseapp.com',
    storageBucket: 'maxliss.firebasestorage.app',
    measurementId: 'G-DJXM290VR0',
  );
}
